dist: xenial

language: cpp

matrix:
  include:
    # linux GCC
    - os: linux
      name: Linux GCC
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - lcov
            - libsdl2-dev
            - libsdl2-image-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - liblua5.3-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        -
        # linux CLANG
    - os: linux
      compiler: clang
      name: Linux Clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libsdl2-dev
            - libsdl2-image-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - liblua5.3-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    # OSX GCC
    - os: osx
      osx_image: xcode9.4
      name: OSX GCC
      addons:
        homebrew:
          packages:
            - sdl2
            - sdl2_image
            - lua@5.3
          update: true
      env:
        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

    # OSX CLANG
    - os: osx
      osx_image: xcode9.4
      name: OSX Clang
      addons:
        homebrew:
          packages:
            - sdl2
            - sdl2_image
            - lua@5.3
          update: true

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
